### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by MarisaKirisame** [Kalimehtar/gls#2]
marisa@lolisa:~$ raco pkg install gls
Resolving "gls" via http://download.racket-lang.org/releases/6.2/catalog/
Resolving "gls" via http://pkgs.racket-lang.org
Downloading https://github.com/Kalimehtar/gls/tarball/3305a1a6ead772b1a04d686ab96e31295cf447e4
raco setup: version: 6.2 [3m]
raco setup: installation name: 6.2
raco setup: variants: 3m
raco setup: main collects: /usr/share/racket/collects
raco setup: collects paths: 
raco setup:   /home/marisa/.racket/6.2/collects
raco setup:   /usr/share/racket/collects
raco setup: main pkgs: /usr/share/racket/pkgs
raco setup: pkgs paths: 
raco setup:   /usr/share/racket/pkgs
raco setup:   /home/marisa/.racket/6.2/pkgs
raco setup: links files: 
raco setup:   /usr/share/racket/links.rktd
raco setup:   /home/marisa/.racket/6.2/links.rktd
raco setup: main docs: /usr/share/doc/racket
raco setup: --- updating info-domain tables ---
raco setup: --- pre-installing collections ---
raco setup: --- installing foreign libraries ---
raco setup: --- installing shared files ---
raco setup: --- compiling collections ---
raco setup: --- parallel build using 4 jobs ---
raco setup: 3 making: <pkgs>/gls/gls
.racket/6.2/pkgs/gls/gls/types.rkt:55:8: module: identifier is already imported
  at: ==
  in: (define-values (==) eq-type)
  compilation context...:
   /home/marisa/.racket/6.2/pkgs/gls/gls/types.rkt
   /home/marisa/.racket/6.2/pkgs/gls/gls/runtime-library.rkt
  context...:
   /usr/share/racket/collects/compiler/cm.rkt:341:0: compile-zo*
   /usr/share/racket/collects/compiler/cm.rkt:556:26
   /usr/share/racket/collects/compiler/cm.rkt:548:42
   /usr/share/racket/collects/compiler/cm.rkt:513:0: maybe-compile-zo
   /usr/share/racket/collects/compiler/cm.rkt:628:2: do-check
   /usr/share/racket/collects/compiler/cm.rkt:744:4: compilation-manager-load-handler
   standard-module-name-resolver
   /usr/share/racket/collects/compiler/cm.rkt:341:0: compile-zo*
   /usr/share/racket/collects/compiler/cm.rkt:556:26
   /usr/share/racket/collects/compiler/cm.rkt:548:42
   /usr/share/racket/collects/compiler/cm.rkt:513:0: maybe-compile-zo
   /usr/share/racket/collects/compiler/cm.rkt:628:2: do-check
   /usr/share/racket/collects/compiler/cm.rkt:708:4
   /usr/share/racket/collects/setup/parallel-do.rkt:431:20: loop
.racket/6.2/pkgs/gls/gls/types.rkt:55:8: module: identifier is already imported
  at: ==
  in: (define-values (==) eq-type)
  context...:
   standard-module-name-resolver
   /usr/share/racket/collects/compiler/cm.rkt:341:0: compile-zo*
   /usr/share/racket/collects/compiler/cm.rkt:556:26
   /usr/share/racket/collects/compiler/cm.rkt:548:42
   /usr/share/racket/collects/compiler/cm.rkt:513:0: maybe-compile-zo
   /usr/share/racket/collects/compiler/cm.rkt:628:2: do-check
   /usr/share/racket/collects/compiler/cm.rkt:708:4
   /usr/share/racket/collects/setup/parallel-do.rkt:431:20: loop
.racket/6.2/pkgs/gls/gls/types.rkt:55:8: module: identifier is already imported
  at: ==
  in: (define-values (==) eq-type)
  context...:
   standard-module-name-resolver
.racket/6.2/pkgs/gls/gls/types.rkt:55:8: module: identifier is already imported
  at: ==
  in: (define-values (==) eq-type)
  context...:
   standard-module-name-resolver
   /usr/share/racket/collects/compiler/cm.rkt:341:0: compile-zo*
   /usr/share/racket/collects/compiler/cm.rkt:556:26
   /usr/share/racket/collects/compiler/cm.rkt:548:42
   /usr/share/racket/collects/compiler/cm.rkt:513:0: maybe-compile-zo
   /usr/share/racket/collects/compiler/cm.rkt:628:2: do-check
   /usr/share/racket/collects/compiler/cm.rkt:708:4
   /usr/share/racket/collects/setup/parallel-do.rkt:431:20: loop
.racket/6.2/pkgs/gls/gls/types.rkt:55:8: module: identifier is already imported
  at: ==
  in: (define-values (==) eq-type)
  compilation context...:
   /home/marisa/.racket/6.2/pkgs/gls/gls/types.rkt
   /home/marisa/.racket/6.2/pkgs/gls/gls/main.rkt
   /home/marisa/.racket/6.2/pkgs/gls/gls/test.rkt
  context...:
   /usr/share/racket/collects/compiler/cm.rkt:341:0: compile-zo*
   /usr/share/racket/collects/compiler/cm.rkt:556:26
   /usr/share/racket/collects/compiler/cm.rkt:548:42
   /usr/share/racket/collects/compiler/cm.rkt:513:0: maybe-compile-zo
   /usr/share/racket/collects/compiler/cm.rkt:628:2: do-check
   /usr/share/racket/collects/compiler/cm.rkt:744:4: compilation-manager-load-handler
   standard-module-name-resolver
   /usr/share/racket/collects/compiler/cm.rkt:341:0: compile-zo*
   /usr/share/racket/collects/compiler/cm.rkt:556:26
   /usr/share/racket/collects/compiler/cm.rkt:548:42
   /usr/share/racket/collects/compiler/cm.rkt:513:0: maybe-compile-zo
   /usr/share/racket/collects/compiler/cm.rkt:628:2: do-check
   /usr/share/racket/collects/compiler/cm.rkt:744:4: compilation-manager-load-handler
   standard-module-name-resolver
   /usr/share/racket/collects/compiler/cm.rkt:341:0: compile-zo*
   /usr/share/racket/collects/compiler/cm.rkt:556:26
   ...
raco setup: --- creating launchers ---
raco setup: --- installing man pages ---
raco setup: --- building documentation ---
raco setup: --- installing collections ---
raco setup: --- post-installing collections ---
raco setup: --- summary of errors ---
raco setup: error: during making for <pkgs>/gls/gls
raco setup:   .racket/6.2/pkgs/gls/gls/types.rkt:55:8: module: identifier is already imported
raco setup:     at: ==
raco setup:     in: (define-values (==) eq-type)
raco setup:     compiling: <pkgs>/gls/gls/types.rkt
raco setup: error: during making for <pkgs>/gls/gls
raco setup:   .racket/6.2/pkgs/gls/gls/types.rkt:55:8: module: identifier is already imported
raco setup:     at: ==
raco setup:     in: (define-values (==) eq-type)
raco setup: error: during making for <pkgs>/gls/gls
raco setup:   .racket/6.2/pkgs/gls/gls/types.rkt:55:8: module: identifier is already imported
raco setup:     at: ==
raco setup:     in: (define-values (==) eq-type)
raco setup: error: during making for <pkgs>/gls/gls
raco setup:   .racket/6.2/pkgs/gls/gls/types.rkt:55:8: module: identifier is already imported
raco setup:     at: ==
raco setup:     in: (define-values (==) eq-type)
raco setup: error: during making for <pkgs>/gls/gls
raco setup:   .racket/6.2/pkgs/gls/gls/types.rkt:55:8: module: identifier is already imported
raco setup:     at: ==
raco setup:     in: (define-values (==) eq-type)
raco setup:     compiling: <pkgs>/gls/gls/types.rkt
raco pkg install: packages installed, although setup reported errors
marisa@lolisa:~$

**Comment by Kalimehtar** [comment]
Fixed. Removed racket/match from require in types.rkt.

Strange, but DrRacket didn't show the error.

**Comment by MarisaKirisame** [comment]
would you mind clicking the "update" on racket pkgs server? Thx...

**Comment by Kalimehtar** [comment]
done
