### ISSUE TITLE
Make subtype? more expressive

### ISSUE THREAD

**Issue by MarisaKirisame** [Kalimehtar/gls#4]
https://github.com/lolisa/Chinese-4-Stratego/blob/master/main.rkt
The code report that I have ambiguity even though there are subtype.
Upon investigation, I think the problem is due to (subtype? (compose x y) (compose x y)) return false.
While the problem can be solve directly (providing a immediate name), this is a rather common usage, and could be hard-coded in subtype?. (Or better yet, provide an interface to extend rules in subtype?, but this require more coding)

**Comment by Kalimehtar** [comment]
> this is a rather common usage, and could be hard-coded in subtype?

If you want to have a higher order function as a predicate, you should provide stable results for it. I mean (eq? (compose x y) (compose x y)) should be #t

You may do

```
(require memoize)
(define/memo (compose f g) (lambda (x) (f (g x))))
```

Otherwise, you cannot compare them in `subtype?`. Or how do you want to compare two procedures?

**Comment by MarisaKirisame** [comment]
Sure thx.
I do not mean that we should compare the two completely, just that we should make ad hoc specialization for compose, just as we do so for and, or...

**Comment by Kalimehtar** [comment]
> we should make ad hoc specialization for compose

Then `compose` must return a struct. Considering that in common case, we cannot say if one result of `compose` is subtype of other result of compose (like for `and?` and `or?`). So only usable case is, when `compose` result should be identical to the other `compose` result. But in this case `memoize` is much simpler (no struct is needed, almost no changes to the definition of `compose`)

**Comment by MarisaKirisame** [comment]
Thx

**Comment by MarisaKirisame** [comment]
I think we can still say so:
f <: g -> (compose f h) <: (compose g h)
although I do not have demand for this, it certainly can be useful, like
compose integer? get-num <: compose complex? get-num

**Comment by MarisaKirisame** [comment]
if f and g are partial function (input -> output -> Prop with some uniqueness definition),
foall x, f x res -> g x res -> (compose h f) <: (compose h g) is a debatable rule, albeit much difficult to implement

**Comment by Kalimehtar** [comment]
Commited new version with `compose?` function.
