### ISSUE TITLE
compose? syntax question

### ISSUE THREAD

**Issue by MarisaKirisame** [Kalimehtar/gls#7]
(defgeneric collide!
  (method [(attack (compose? (list normal-piece? piece))) (defense (compose? (list normal-piece? piece)))](if %28<= %28power %28piece attack%29%29 %28power %28piece defense%29%29%29 %28kill! attack%29 void)
          (if (<= (power (piece defense)) (power (piece attack))) (kill! defense) void))
  (method [(attack (compose? (list bomb? piece))) (defense true)](kill! attack)
          (kill! defense))
  (method [(attack true) (defense (compose? (list bomb? piece)))](kill! attack)
          (kill! defense))
  (method [(attack (compose? (list bomb? piece))) (defense (compose? (list bomb? piece)))](kill! attack)
          (kill! defense)))
I think (compose? (list bomb? piece)) should be written as (compose? bomb? piece).

**Comment by Kalimehtar** [comment]
Agree. Fixed.
