### ISSUE TITLE
the package still build with dependency problem 

### ISSUE THREAD

**Issue by MarisaKirisame** [Kalimehtar/gls#8]
http://pkgs.racket-lang.org/#[gls]

**Comment by Kalimehtar** [comment]
I see there "The time is now Tuesday, December 22nd, 2015 6:16:00am"

Would you try to build current version to check this?

**Comment by MarisaKirisame** [comment]
My build went clear. IMO The easiest way to test it is to click the upload button and start the pkg build...

**Comment by Kalimehtar** [comment]
I don't think, that this should be forced (with reuploading the package). As far as I understand, it rebuilds once in several days automatically. I'll just wait and it will be fixed.
